openapi: 3.0.3
info:
  title: xGoal Inference Service
  version: 1.0.0
  description: |
    FastAPI service exposing xGoal logistic regression inference endpoints.
servers:
  - url: http://localhost:8000

tags:
  - name: Matches
  - name: Predictions
  - name: Shots

paths:
  /matches:
    get:
      tags: [Matches]
      summary: List matches available to the tutor UI
      operationId: listMatches
      responses:
        '501':
          description: Listing matches is not yet implemented

  /matches/{match_id}/lineups:
    get:
      tags: [Matches]
      summary: Get starting lineups for a match
      operationId: getMatchLineups
      parameters:
        - name: match_id
          in: path
          required: true
          schema: { type: string }
      responses:
        '501':
          description: Match lineup retrieval is not yet implemented

  /matches/{match_id}/summary:
    post:
      tags: [Matches]
      summary: Enqueue asynchronous tactical summary generation for a match
      description: >
        Produces a tactical summary for each team ("home_team", "away_team")
        based on individual shot summaries from `predict_shots` and player summaries.
        Output (when ready) includes "positives", "improvements", "best_player", "improve_player".
        This endpoint is asynchronous and immediately returns a generation identifier.
      operationId: enqueueMatchSummary
      parameters:
        - name: match_id
          in: path
          required: true
          schema: { type: string }
      responses:
        '202':
          description: Summary generation enqueued
          headers:
            Location:
              description: Polling URL for this job (if/when a status endpoint is added)
              schema: { type: string, format: uri }
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchSummarySubmissionResponse'
              examples:
                default:
                  value:
                    generation_id: "gen_01HZX3W1QZ1A3ZKQ2C7C0S3V7R"
                    match_id: "SB-0001"
                    status: "queued"
                    status_url: "http://localhost:8000/matches/SB-0001/summary?generation_id=gen_01HZX3W1..."
                    enqueued_at: "2025-10-31T12:00:00Z"
        '501':
          description: Match summary generation is not yet implemented

  /matches/{match_id}/players/{player_id}/summary:
    post:
      tags: [Matches]
      summary: Generate a tactical summary for a player within a match
      description: >
        Produces a tactical summary for the specified player based on individual
        shot summaries from `predict_shots` where the player was involved.
        Output includes "positives" and "improvements".
      operationId: generateMatchPlayerSummary
      parameters:
        - name: match_id
          in: path
          required: true
          schema: { type: string }
        - name: player_id
          in: path
          required: true
          schema: { type: string }
      responses:
        '501':
          description: Match player summary generation is not yet implemented

  /predict_shots:
    post:
      tags: [Predictions]
      summary: Predict xG and explanation using the managed prompt
      operationId: predictShots
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShotPredictionRequest'
      responses:
        '200':
          description: Predictions and explanation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShotPredictionResponse'
        '400':
          description: At least one shot must be provided
        '502':
          description: Failed to retrieve a response from the LLM

  /predict_shots_with_prompt:
    post:
      tags: [Predictions]
      summary: Predict xG and explanation with a custom prompt override
      operationId: predictShotsWithPrompt
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShotPredictionWithPromptRequest'
      responses:
        '200':
          description: Predictions and explanation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShotPredictionResponse'
        '400':
          description: At least one shot must be provided
        '502':
          description: Failed to retrieve a response from the LLM

  /match/{match_id}/shots:
    get:
      tags: [Shots]
      summary: Get cached shot predictions for a match
      description: Returns the last cached result produced by /predict_shots for this match.
      operationId: getMatchShots
      parameters:
        - name: match_id
          in: path
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Cached predictions for the match
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShotPredictionResponse'
        '404':
          description: No cached predictions for match

  /shots/{shot_id}:
    get:
      tags: [Shots]
      summary: Get full detail for a specific shot
      description: Includes positions and explanations (when implemented).
      operationId: getShotDetail
      parameters:
        - name: shot_id
          in: path
          required: true
          schema: { type: string }
      responses:
        '501':
          description: Shot detail retrieval is not yet implemented

components:
  schemas:
    # ---------- Async match summary submission (for POST /matches/{match_id}/summary) ----------
    MatchSummarySubmissionResponse:
      type: object
      required: [generation_id, match_id, status, status_url, enqueued_at]
      properties:
        generation_id:
          type: string
          description: Server-assigned identifier for the generation job
        match_id:
          type: string
        status:
          type: string
          enum: ["queued", "running"]
        status_url:
          type: string
          format: uri
          description: Absolute URL to poll job status (reserved for a future GET status endpoint)
        enqueued_at:
          type: string
          format: date-time

    # ---------- Prediction request/response (current app models) ----------
    ShotPredictionRequest:
      type: object
      required: [shots, model]
      properties:
        shots:
          type: array
          items:
            $ref: '#/components/schemas/ShotFeatures'
        model:
          $ref: '#/components/schemas/LogisticRegressionModel'
        llm_model:
          type: string
          nullable: true
          description: Optional override for the LLM model to use

    ShotPredictionWithPromptRequest:
      allOf:
        - $ref: '#/components/schemas/ShotPredictionRequest'
        - type: object
          required: [prompt]
          properties:
            prompt:
              type: string
              description: Custom prompt text to send to the language model

    ShotPredictionResponse:
      type: object
      required: [shots, explanation, llm_model]
      properties:
        shots:
          type: array
          items:
            $ref: '#/components/schemas/ShotPrediction'
        explanation:
          type: string
          description: Natural-language explanation returned by the language model
        llm_model:
          type: string
          description: Name of the model that produced the explanation

    ShotPrediction:
      type: object
      required: [xg, reason_codes]
      properties:
        shot_id:
          type: string
          nullable: true
        match_id:
          type: string
          nullable: true
        xg:
          type: number
          format: float
          description: Expected goal probability for the shot
        reason_codes:
          type: array
          items:
            $ref: '#/components/schemas/ReasonCode'

    # ---------- Shared domain from old contract (kept for future implementations) ----------
    Team:
      type: object
      properties:
        id: { type: string }
        name: { type: string }
        short_name: { type: string, nullable: true }

    Player:
      type: object
      properties:
        id: { type: string }
        name: { type: string }
        jersey_number: { type: integer, nullable: true }
        team_id: { type: string, nullable: true }
        position: { type: string, nullable: true }

    LineupPlayer:
      type: object
      properties:
        player: { $ref: '#/components/schemas/Player' }
        is_starter: { type: boolean }
        jersey_number: { type: integer, nullable: true }
        position_name: { type: string, nullable: true }
        sort_order: { type: integer, nullable: true }

    LineupTeam:
      type: object
      properties:
        team: { $ref: '#/components/schemas/Team' }
        starters:
          type: array
          items: { $ref: '#/components/schemas/LineupPlayer' }
        bench:
          type: array
          items: { $ref: '#/components/schemas/LineupPlayer' }

    MatchLineups:
      type: object
      properties:
        home: { $ref: '#/components/schemas/LineupTeam' }
        away: { $ref: '#/components/schemas/LineupTeam' }

    # ---------- Explanations & reason codes ----------
    ReasonCode:
      type: object
      required: [feature, value, coefficient, contribution]
      properties:
        feature: { type: string }
        value: { type: number, format: float }
        coefficient: { type: number, format: float }
        contribution: { type: number, format: float }

    LogisticRegressionModel:
      type: object
      required: [intercept, coefficients]
      properties:
        intercept:
          type: number
          format: float
          description: Intercept term of the logistic regression model
        coefficients:
          type: object
          additionalProperties:
            type: number
            format: float
          description: Mapping of feature names to coefficient values

    ShotFeatures:
      type: object
      required: [start_x, start_y]
      properties:
        shot_id:
          type: string
          nullable: true
          description: Identifier of the shot within the match or dataset
        match_id:
          type: string
          nullable: true
          description: Identifier of the match the shot belongs to
        start_x: { type: number, format: float }
        start_y: { type: number, format: float }
        is_set_piece: { type: boolean, default: false }
        is_corner: { type: boolean, default: false }
        is_free_kick: { type: boolean, default: false }
        first_time: { type: boolean, nullable: true }
        under_pressure: { type: boolean, nullable: true }
        body_part: { type: string, nullable: true }
        ff_keeper_x: { type: number, format: float, nullable: true }
        ff_keeper_y: { type: number, format: float, nullable: true }
        ff_opponents: { type: number, format: float, nullable: true }
        freeze_frame_available: { type: integer, nullable: true }
        ff_keeper_count: { type: integer, nullable: true }
        one_on_one: { type: boolean, nullable: true }
        open_goal: { type: boolean, nullable: true }
        follows_dribble: { type: boolean, nullable: true }
        deflected: { type: boolean, nullable: true }
        aerial_won: { type: boolean, nullable: true }
